config/routes.rb
Rails.application.routes.draw do

  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end

  root 'restaurants#index'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews, :dependent => :destroy

  @allowed_category = ["chinese", "italian", "japanese", "french", "belgian"]

  validates :name, :address, :category, presence: true
  validates :category, :inclusion=> { :in => @allowed_category }
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant

  @allowed_rating = [0, 1, 2, 3, 4, 5]
  validates :content, :rating, :restaurant_id, presence: true
  validates :rating, :inclusion=> { :in => @allowed_rating }
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      # flash[:dave] = "Restaurant successfully created"
      redirect_to @restaurant
    else
       render :new
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path
    # flash[:dave] = "Restaurant boom"
  end

  protected

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_restaurant, only: [ :new, :create ]

  def new
    @review = Review.new
  end

  def create
    @review = @restaurant.reviews.build(review_params)
    if @review.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  protected

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yelpr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= flash[:dave] %>

<%= yield %>

</body>
</html>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>
(<%= link_to 'create a new restaurant', new_restaurant_path %>)
<hr>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Address</th>
      <th>Phone Number</th>
      <th>Category</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @restaurants.each do |restaurant| %>
    <tr>
      <td><%= restaurant.id %></td>
      <td><%= restaurant.name %></td>
      <td><%= restaurant.address %></td>
      <td><%= restaurant.phone_number %></td>
      <td><%= restaurant.category %></td>
      </td>
      <td><%= link_to('show', restaurant_path(restaurant)) %> |
        <%= link_to('delete', restaurant_path(restaurant), method: :delete)%> |
        <%= link_to('add review', new_restaurant_review_path(restaurant)) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/restaurants/new.html.erb
<h1>Create a new restaurant</h1>
<hr>
<%= form_for(@restaurant) do |f| %>

  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :address %>
<%= f.text_field :address %>
<%= f.label :phone_number %>
<%= f.text_field :phone_number %>
<%= f.label :category %>
<%= f.select :category, options_for_select(%w[chinese french belgian italian japanese]) %>
<%= f.submit %>


<% end %>

app/views/restaurants/show.html.erb
<h1>Restaurant <strong><%= @restaurant.name %></strong> (id = <%= @restaurant.id %>)</h1>
<hr>
<p>Address: <strong><%= @restaurant.address %></strong></p>
<p>Phone number: <strong><%= @restaurant.phone_number %></strong></p>
<p>Category: <strong><%= @restaurant.category %></strong></p>






<hr>
<% @restaurant.reviews.each do |review| %>
<p><%= review.rating %> | <%= review.content %></p>
<% end %>
<hr>
<p><%= link_to "Back", restaurants_path %>

app/views/reviews/new.html.erb
<h1>New review for restaurant</h1>
<hr>
<%= form_for [@restaurant, @review] do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.label :rating %>
  <%= f.text_field :rating %>
  <%= f.submit "add a review" %>
<% end %>